upgrade to nodejs 18.18.2
LibertyDSNP/parquetjs pull request #101
Opened 2023-11-17 00:12 UTC by shannonwells

Problem
=======
Upgrade to nodejs 18+.

Solution
========
Used last patch version of [nodejs 18](https://nodejs.org/en/about/previous-releases)

Change summary:
---------------
changed .tool-versions, changed package.json and ran `npm install` to update package-lock.json

Steps to Verify:
----------------
CI should pass

2023-11-17 15:52 UTC, wilwade requested changes
Found a few more places to update, but everything is working

- Ran locally
- Built
- Ran thrift

2023-11-17 21:56 UTC, shannonwells commented on .tool-versions
> +nodejs 18.18.2
I created another upgrade issue with these items in a checklist.

2023-11-17 22:08 UTC, shannonwells commented on .tool-versions
> +nodejs 18.18.2
looks like CI is ok with the actions versions for now.  maybe add it to the next upgrade issue?

2023-11-17 22:08 UTC, wilwade approved these changes
🚢

2023-11-17 22:08 UTC, wilwade commented on .tool-versions
> +nodejs 18.18.2
That sounds good. More of an Actions upgrade issue.

2023-11-17 22:09 UTC, wilwade approved these changes
Approving to make sure to capture all the changes

2023-11-17 22:09 UTC, merged

2024-01-29 01:43 UTC, 0Ams commented
Why did you put a limit on the version?
I'm curious about the restrictions on the relief of 18.15.0 even though it operates normally